@startuml
box
    participant Spiller1
    participant Spiller2
end box

Spiller1 <- Yatzoo: Tildel runder
Spiller2 <- Yatzoo: Tildel runder

note left : Kan være flere enn 2 spillere

loop for alle runder
    loop for alle spillere
        Yatzoo -> Tekstgrensesnitt : Skriv ut hvem det er sin tur
        Yatzoo -> Spiller1: Spiller runde
        loop 3
            Spiller1 -> Runde : velger terninger som skal kastes på nytt
            Runde -> no.hvl.dat109.Terning : kast terninger
            Spiller1 -> Tekstgrensesnitt : Skriv ut informasjon
        end
    end
end

Yatzoo -> Yatzoo : finn vinner

@enduml